/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * System-prompt snapshot tests for the Copilot provider.
 *
 * Each model in {@link SNAPSHOT_MODELS} gets one E2E turn, and the full
 * assembled system prompt + tool list is saved via `assertSnapshot`. When the
 * prompt changes (SDK bump, prompt override update), the test fails with a diff
 * and you accept the new baseline in the test explorer.
 *
 * Recording:
 *   AGENT_HOST_REPLAY_RECORD=1 ./scripts/test-integration.sh --run \
 *     src/vs/platform/agentHost/test/node/e2e/providers/copilotPromptsE2E.integrationTest.ts
 *
 * Replay (no token needed):
 *   ./scripts/test-integration.sh --run \
 *     src/vs/platform/agentHost/test/node/e2e/providers/copilotPromptsE2E.integrationTest.ts
 */

import assert from 'assert';
import { mkdtemp, mkdir, rm, unlink, writeFile } from 'fs/promises';
import { tmpdir } from 'os';
import { URI } from '../../../../../../base/common/uri.js';
import { FileAccess } from '../../../../../../base/common/network.js';
import { ActionType } from '../../../../common/state/sessionActions.js';
import { MessageKind, ToolCallConfirmationReason, buildDefaultChatUri } from '../../../../common/state/sessionState.js';
import {
	AgentHostE2EServerLease,
	createRealSession,
	type IAgentHostE2EProviderConfig,
} from '../harness/agentHostE2ETestHarness.js';
import { TestProtocolClient } from '../../serverIntegrationTestHelpers.js';

const COPILOT_CONFIG: IAgentHostE2EProviderConfig = {
	suiteTitle: 'Copilot Prompt Snapshots',
	provider: 'copilotcli',
	scheme: 'copilotcli',
	shellToolName: 'bash',
	subagentToolNames: ['task'],
	exitPlanModeToolName: 'exit_plan_mode',
	enabled: true,
	supportsWorktreeIsolation: false,
	supportsHostTerminalTool: false,
	supportsSubagents: false,
	supportsSideChats: false,
	supportsPlanMode: false,
	supportsMultipleChats: false,
	supportsChatFork: false,
	supportsChatForkE2E: false,
	stableNewScenarioResponse: true,
};

const RECORD_ONLY = process.env['AGENT_HOST_REPLAY_RECORD'] === '1';

/** Add models here to capture their full assembled prompt. */
const SNAPSHOT_MODELS = [
	'default',
	'claude-opus-5',
	'gpt-5.6-sol',
] as const;

suite('ahp-prompts', function () {

	let client: TestProtocolClient;
	let lease: AgentHostE2EServerLease | undefined;
	const createdSessions: string[] = [];
	const tempDirs: string[] = [];

	suiteSetup(function () {
		lease = new AgentHostE2EServerLease(COPILOT_CONFIG);
	});

	setup(async function () {
		this.timeout(60_000);
		if (!lease) {
			throw new Error('Lease not initialized');
		}
		({ client } = await lease.acquire(this.currentTest?.title ?? 'unknown'));
	});

	teardown(async function () {
		this.timeout(60_000);
		if (!lease) {
			throw new Error('Lease not initialized');
		}
		await lease.release(createdSessions);
		for (const dir of tempDirs) {
			try { await rm(dir, { recursive: true, force: true }); } catch { /* best effort */ }
		}
		tempDirs.length = 0;
	});

	suiteTeardown(async function () {
		this.timeout(30_000);
		await lease?.dispose();
		// Clean up YAML capture files generated by the harness — they're unused.
		for (const model of SNAPSHOT_MODELS) {
			const slug = `copilotcli-${model}`.replace(/\./g, '-');
			try { await unlink(`src/vs/platform/agentHost/test/node/e2e/captures/${slug}.yaml`); } catch { /* may not exist */ }
		}
	});

	for (const model of SNAPSHOT_MODELS) {
		// Record-only: the SDK's foundation prompt differs between the live SDK
		// (recording) and the bundled SDK (replay), so replay would always mismatch.
		(RECORD_ONLY ? test : test.skip)(`${model}`, async function () {
			this.timeout(120_000);

			const workspaceDir = await mkdtemp(`${tmpdir()}/ahp-prompt-snap-`);
			tempDirs.push(workspaceDir);

			const sessionUri = await createRealSession(client, COPILOT_CONFIG, `prompt-snap-${model}`, createdSessions, URI.file(workspaceDir));
			await driveTurnWithModel(client, sessionUri, model);

			const body = lease!.observedModelRequestBodies.at(-1) ?? '';
			assert.ok(body.length > 0, 'No model request body captured');

			const parsed = JSON.parse(body) as { model?: string };
			const modelId = parsed.model ?? model;
			const snapshot = formatRequestSnapshot(body);
			await writeSnapshot(`${modelId}-prompt.snap`, snapshot);
		});
	}
});

/** Dispatches a turn with an explicit model selection and waits for completion. */
async function driveTurnWithModel(c: TestProtocolClient, sessionUri: string, model: string): Promise<void> {
	const chatUri = buildDefaultChatUri(sessionUri);
	c.clearReceived();
	c.dispatch({
		channel: chatUri,
		clientSeq: 1,
		action: {
			type: ActionType.ChatTurnStarted,
			turnId: `turn-${model}`,
			startedAt: '2025-01-01T00:00:00.000Z',
			message: {
				text: 'Say exactly "ok"',
				origin: { kind: MessageKind.User },
				...(model !== 'default' && { model: { id: model } }),
			},
		},
	});

	// Drive until turnComplete, auto-confirming any tool calls
	const seenNotifications = new Set<object>();
	let nextClientSeq = 2;
	while (true) {
		const n = await c.waitForNotification(notification => {
			if (seenNotifications.has(notification as object)) { return false; }
			const envelope = notification as { params?: { action?: { type?: string } } };
			const type = envelope?.params?.action?.type;
			return type === 'chat/turnComplete' || type === 'chat/toolCallReady' || type === 'chat/error';
		}, 90_000);
		seenNotifications.add(n as object);

		const envelope = n as { params?: { action?: { type?: string; turnId?: string; toolCallId?: string } } };
		const type = envelope?.params?.action?.type;
		if (type === 'chat/turnComplete' || type === 'chat/error') {
			break;
		}
		if (type === 'chat/toolCallReady') {
			c.dispatch({
				channel: chatUri,
				clientSeq: nextClientSeq++,
				action: { type: ActionType.ChatToolCallConfirmed, turnId: envelope.params!.action!.turnId!, toolCallId: envelope.params!.action!.toolCallId!, approved: true, confirmed: ToolCallConfirmationReason.Setting },
			});
		}
	}
}

function formatRequestSnapshot(rawBody: string): string {
	const request = JSON.parse(rawBody) as {
		model?: string;
		system?: unknown;
		tools?: Array<{ name?: string; description?: string; input_schema?: unknown }>;
		messages?: Array<{ role?: string; content?: unknown }>;
	};

	const lines: string[] = [];
	lines.push('### Model');
	lines.push(request.model ?? '(unknown)');
	lines.push('');

	lines.push('### System');
	lines.push('~~~md');
	lines.push(extractSystemText(request.system));
	lines.push('~~~');
	lines.push('');

	if (request.tools && request.tools.length > 0) {
		lines.push(`### Tools (${request.tools.length})`);
		lines.push('');
		for (const tool of request.tools) {
			lines.push(`#### ${tool.name ?? '(unnamed)'}`);
			if (tool.description) {
				lines.push(tool.description);
			}
			if (tool.input_schema) {
				lines.push('```json');
				lines.push(JSON.stringify(tool.input_schema, null, 2));
				lines.push('```');
			}
			lines.push('');
		}
	}

	// Capture any pre-turn messages (reminders, system injections)
	if (request.messages && request.messages.length > 0) {
		lines.push(`### Messages (${request.messages.length})`);
		lines.push('');
		for (const msg of request.messages) {
			lines.push(`#### [${msg.role ?? 'unknown'}]`);
			lines.push(extractContentText(msg.content));
			lines.push('');
		}
	}

	return normalizeVolatile(lines.join('\n'));
}

function extractSystemText(system: unknown): string {
	return extractContentText(system);
}

function extractContentText(content: unknown): string {
	if (typeof content === 'string') {
		return content;
	}
	if (Array.isArray(content)) {
		return content
			.map(block => {
				if (typeof block === 'string') { return block; }
				if (typeof block === 'object' && block !== null && typeof (block as Record<string, unknown>).text === 'string') {
					return (block as { text: string }).text;
				}
				return '';
			})
			.filter(Boolean)
			.join('\n');
	}
	return '';
}

function normalizeVolatile(text: string): string {
	return text
		.replace(/The current date is .*/g, '(Date removed from snapshot)')
		.replace(/<current_datetime>[^<]+<\/current_datetime>/g, '<current_datetime>(removed)</current_datetime>')
		.replace(/You are powered by the model named .+\./g, '(Model identity removed from snapshot)')
		.replace(/The exact model ID is .+\./g, '(Model ID removed from snapshot)')
		.replace(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi, '(uuid)')
		.replace(/\/var\/folders\/[^\s]+/g, '(tmpdir)')
		.replace(/\/tmp\/[^\s]+/g, '(tmpdir)')
		.replace(/C:\\Users\\[^\s]+/g, '(tmpdir)')
		.replace(/\/Users\/[^\s/]+/g, '/Users/(user)');
}

const SNAPSHOTS_DIR = FileAccess.asFileUri('vs/platform/agentHost/test/node/e2e/providers/__snapshots__').fsPath
	.replace('/out/', '/src/');

async function writeSnapshot(filename: string, content: string): Promise<void> {
	await mkdir(SNAPSHOTS_DIR, { recursive: true });
	await writeFile(`${SNAPSHOTS_DIR}/${filename}`, content, 'utf-8');
}
